name: Versioning

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get current version
        id: vars
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "CURRENT_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Increment version
        id: increment
        run: |
          VERSION=${{ env.CURRENT_VERSION }}
          MAJOR=$(echo $VERSION | cut -d. -f1 | cut -dv -f2)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          PATCH=$((PATCH+1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "Version incremented to $NEW_VERSION"

      - name: Debug environment
        run: |
          echo "GH_TOKEN=${GH_TOKEN}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"

      - name: Create and push new tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          NEW_VERSION=${{ env.NEW_VERSION }}
          git tag $NEW_VERSION
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} $NEW_VERSION

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: "Release ${{ env.NEW_VERSION }}"
          draft: false
          prerelease: false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
